# Generated by Django 4.2.11 on 2024-03-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_confirmed',
        ),
    ]
