# Generated by Django 4.2.11 on 2024-05-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Most Active Users',
                'verbose_name_plural': 'Most Active User Stats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
        ),
    ]
