# Generated by Django 4.2.11 on 2024-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=20)),
            ],
        ),
    ]
