# Generated by Django 4.2.11 on 2024-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AItasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledsound',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='labeledsound',
            name='filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labeledsound',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
