# Generated by Django 4.2.11 on 2024-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AItasks', '0002_alter_labeledsound_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
            ],
        ),
    ]
