# Generated by Django 4.2.11 on 2024-05-11 06:33

import AItasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AItasks', '0004_themesound_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledsound',
            name='file_path',
            field=models.FileField(upload_to=AItasks.models.sound_storage),
        ),
        migrations.AlterField(
            model_name='themesound',
            name='file_path',
            field=models.FileField(upload_to=AItasks.models.theme_storage),
        ),
    ]
