# Generated by Django 4.2.11 on 2024-05-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AItasks', '0005_alter_labeledsound_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeledsound',
            old_name='file_path',
            new_name='sound_file',
        ),
        migrations.RenameField(
            model_name='themesound',
            old_name='file_path',
            new_name='sound_file',
        ),
    ]
