# Generated by Django 4.2.11 on 2024-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AItasks', '0006_rename_file_path_labeledsound_sound_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledsound',
            name='filename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='themesound',
            name='filename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
