# Generated by Django 4.2.11 on 2024-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationinfo',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
