# Generated by Django 4.2.11 on 2024-04-10 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0003_creationinfo_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
