# Generated by Django 4.2.11 on 2024-04-11 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_image_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
