# Generated by Django 4.2.11 on 2024-04-11 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0005_alter_customization_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='creation_method',
            field=models.CharField(choices=[('AI', 'AI'), ('Set Sequence', 'Set Sequence')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customization',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
