# Generated by Django 4.2.11 on 2024-04-19 11:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0006_alter_customization_creation_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='keywords',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('creation_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.creationinfo')),
            ],
        ),
    ]
