# Generated by Django 4.2.11 on 2024-04-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0007_remove_image_keywords_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='creation_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.image'),
        ),
    ]
