# Generated by Django 4.2.11 on 2024-04-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0008_remove_keyword_keywords_keyword_keyword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='creation_info',
            new_name='image',
        ),
    ]
