# Generated by Django 4.2.11 on 2024-04-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0009_rename_creation_info_keyword_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='image',
        ),
        migrations.AddField(
            model_name='keyword',
            name='creation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='creation.creationinfo'),
            preserve_default=False,
        ),
    ]
