# Generated by Django 4.2.11 on 2024-04-19 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0010_remove_keyword_image_keyword_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
