# Generated by Django 4.2.11 on 2024-04-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0011_keyword_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='creation',
        ),
        migrations.AddField(
            model_name='keyword',
            name='image',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='creation.image'),
            preserve_default=False,
        ),
    ]
