# Generated by Django 4.2.11 on 2024-04-21 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0012_remove_keyword_creation_keyword_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
