# Generated by Django 4.2.11 on 2024-04-21 17:08

import creation.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0013_alter_customization_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='creation_info',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creation_info',
        ),
        migrations.RemoveField(
            model_name='soundclip',
            name='creation_info',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='image',
        ),
        migrations.AddField(
            model_name='creationinfo',
            name='creation_method',
            field=models.CharField(choices=[('AI', 'AI'), ('Set Sequence', 'Set Sequence')], default='AI', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creationinfo',
            name='duration',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creationinfo',
            name='image_file',
            field=models.ImageField(default='1/images/nature-7493878_1280.jpg', upload_to=creation.models.upload_location_images),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creationinfo',
            name='rating',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creationinfo',
            name='sound_file',
            field=models.FileField(default='1/images/mystical-wind-chimes-transition-fx-6327.mp3', upload_to=creation.models.upload_location_sounds),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='creation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='creation.creationinfo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='SoundClip',
        ),
    ]
