# Generated by Django 4.2.11 on 2024-04-21 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0014_remove_image_creation_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationinfo',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
