# Generated by Django 4.2.11 on 2024-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0015_alter_creationinfo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationinfo',
            name='creation_method',
            field=models.CharField(choices=[('Method1', 'Method1'), ('Method2', 'Method2')], max_length=20),
        ),
    ]
