# Generated by Django 4.2.11 on 2024-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0016_alter_creationinfo_creation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationinfo',
            name='creation_method',
            field=models.CharField(choices=[('Randomize Labels', 'Randomize Labels'), ('Randomize Sound Clips', 'Randomize Sound Clips')], max_length=50),
        ),
    ]
