# Generated by Django 4.2.11 on 2024-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0018_keywordsummary_ratingsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationinfo',
            name='creation_method',
            field=models.CharField(choices=[('Plain', 'Plain'), ('Creative', 'Creative')], max_length=50),
        ),
    ]
