# Generated by Django 4.2.11 on 2024-05-11 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0020_alter_keyword_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationinfo',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(2.5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
